create table if not exists public.site_visits (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

create table if not exists public.preorders (
  id bigint generated by default as identity primary key,
  email text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

alter table public.site_visits enable row level security;
alter table public.preorders enable row level security;

create policy "Anyone can register a visit"
on public.site_visits for insert
to anon, authenticated
with check (true);

create policy "Anyone can create a preorder"
on public.preorders for insert
to anon, authenticated
with check (status = 'pending');

create or replace function public.get_site_stats()
returns json
language sql
security definer
set search_path = public
as $$
  select json_build_object(
    'visitors', (select count(*) from public.site_visits),
    'orders', (select count(*) from public.preorders)
  );
$$;

revoke all on function public.get_site_stats() from public;
grant execute on function public.get_site_stats() to anon, authenticated;
